### ISSUE TITLE
Extra Contexts download

### ISSUE THREAD

**Issue by JasonHorkles** [LuckPerms/LuckPermsWeb#273]
Add a download button under the extensions area to the EC module because I'm sure a lot of people don't know the add-on even exists

**Comment by Tobi406** [comment]
I don't think that's the right place, as, technically speaking, ExtraContext is not an extension, but another plugin that adds functionality.

Maybe "Additional Plugins"?

**Comment by JasonHorkles** [comment]
Yeah that works too, it just needs a place on the website somewhere at least

**Comment by Turbotailz** [comment]
IMO ExtraContexts should be an extension but yeah Tobi's right, it is a plugin so should be listed as such.
