### ISSUE TITLE
Make the verbose viewer filter be case insensitive

### ISSUE THREAD

**Issue by emilyy-dev** [LuckPerms/LuckPermsWeb#343]
it`s case sensitive

i hate it

turbo please

**Comment by Turbotailz** [comment]
pr or shut up

Sam Goodger
Front End Engineer
M:  +61 4 9070 8277
E:  sam@goodger.nz
sam.goodger.nz<http://sam.goodger.nz/>
<https://sam.goodger.nz>
________________________________
