### ISSUE TITLE
My Groups are glitched

### ISSUE THREAD

**Issue by Golfistayt** [LuckPerms/LuckPermsWeb#358]
I was trying to add some new permission nodes to my groups when suddenly this happened:
![obraz_2021-05-07_121020](https://user-images.githubusercontent.com/77971759/117434626-31deb480-af2d-11eb-8421-5bd549586e90.png)
Idk why did that occur, but now I just have an empty group default instead of these configured ones.

**Comment by BrainStone** [comment]
Are you using split storage?

**Comment by Turbotailz** [comment]
Need more info on this. Can you share your link again, it expired.

**Comment by Laarryy** [comment]
Closed as stale and no info provided
