### ISSUE TITLE
Build last luckperms webinterface

### ISSUE THREAD

**Issue by lastsamurai26** [LuckPerms/LuckPermsWeb#367]
I can't get the latest Luckperms web interface to build on Windows.

If I try it in the Windows subsystem with the Linux Bash, it works. Even if I try it directly on a Linux server it works. 
Only under Windows 10 I get the following error 
I have installed NVS and use 
{
  'luckperms-web': '2.0.1',
  npm: '7.20.5',
  node: '16.6.1',
  v8: '9.2.230.21-node.19',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV', nghttp3: '0.1.0-DEV'.
}

```
PS D:\Programmierungen\LuckPermsWeb> npm run build

> luckperms-web@2.0.1 build
> vue-cli-service build

 ERROR  Error loading vue.config.js:
 ERROR  TypeError: Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
    at handleProcessResult (D:\Programmierungen\LuckPermsWeb\node_modules\git-describe\lib\git-describe.js:70:20)
    at wrapper (D:\Programmierungen\LuckPermsWeb\node_modules\lodash\lodash.js:5255:19)
    at gitDescribe (D:\Programmierungen\LuckPermsWeb\node_modules\git-describe\lib\git-describe.js:46:16)
    at wrapper (D:\Programmierungen\LuckPermsWeb\node_modules\lodash\lodash.js:5255:19)
    at Object.<anonymous> (D:\Programmierungen\LuckPermsWeb\vue.config.js:5:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

Can someone please tell me where the fault lies here?

**Comment by Turbotailz** [comment]
When you say "Windows 10" do you mean with the Command Prompt terminal or PowerShell?

I haven't tried with either tbh, I always use WSL when I develop on Windows. I can test this out later.

**Comment by lastsamurai26** [comment]
Correct, I use Windows 10 with the Powershell, I also tested it with the Windows CMD. 
In both cases I get this error

I have installed the following tool 
https://github.com/jasongin/nvs/releases

**Comment by Turbotailz** [comment]
I works for me in Windows 10, using Node v12 (downloaded from nodejs.org), it also works when I installed NVS and used 16.6.1... not sure what is going wrong here

**Comment by lastsamurai26** [comment]
OK, that's funny. I just tested it again. on a naked fresh system, strangely it doesn't work there either :( 
I'll see what I can do.

**Comment by lastsamurai26** [comment]
I have tested it on 5 different computers.
Win 10 Pro, Win 10 Ent
as VM, as laptop, or desktop

I always get the same error message :-( 
I don't know why this error message comes up

**Comment by Turbotailz** [comment]
What is the process you are following?

**Comment by lastsamurai26** [comment]
1. create new VM via hyper-v
2. instll win 10 pro 
3. install nvs version 1.6.0
4. start powershell and use the command "nvs" -< select version 16
5. git clone --recursive https://github.com/lucko/LuckPermsWeb.git (i use git a usb env)
6. cd luckpermsweb -> npm install -> npm run build 

this is all what i do

**Comment by Turbotailz** [comment]
Hmm interesting. I haven't really heard of people doing this via VM before.

I wonder if it's NVS that is causing the issue? Have you tried using the NodeJS installer/binary from their website? https://nodejs.org/en/download/

**Comment by lastsamurai26** [comment]
I am doing this in a VM to test what could be causing this.
Maybe it's because of NVS, but why does it work under Linux and Mac also with NVS?

I will try again later with the complete installation of NodeJS.

**Comment by Turbotailz** [comment]
It also works on my Windows machine with NVS (and official Node binary). Although I was only able to run it via cmd not PowerShell (couldn't get PS to recognise the `nvs` command) so I may try that again later.

**Comment by lastsamurai26** [comment]
I have found the problem.
I guess you have the git local environment installed on your PC? 

I didn't but used the USB version of Git and for some reason VUE uses something
from git which is why Git Local needs to be installed. 

Installing git or using the npm run build command in the USB git version fixed the problem.

**Comment by Laarryy** [comment]
Seems that this has been resolved - for anyone in the future that encounters a similar error, see the most recent comment above mine!
