### ISSUE TITLE
Make Copyright button open to new tab.

### ISSUE THREAD

**Issue by ultraic-space** [LuckPerms/LuckPermsWeb#368]
Make Copyright button open to new tab.
![image](https://user-images.githubusercontent.com/61897277/129854452-4ef4fb95-0d13-420c-aaff-ad281af407aa.png)
I've... accidentally pressed this button while trying to add perms... and resetting all that I was working on... too many times now... please...

**Comment by Turbotailz** [comment]
The reason it wasn't opening in a new tab is because it's an internal link, which generally you wouldn't open in a new tab. But I understand that it would be frustrating to accidentally click a link and lose all your progress (something else I plan to address in the future).

**Comment by Laarryy** [comment]
#374 should do it
