### ISSUE TITLE
UUID appears in LuckPerms editor

### ISSUE THREAD

**Issue by SnonSS** [LuckPerms/LuckPermsWeb#398]
What to do if uuid appears in the LuckPerms editor If they are deleted, they appear again, what should I do?

**Comment by SnonSS** [comment]
Here is the uuid: 0995c4b7-fd79-3251-9a86-d8f2af7d281e There are more.

**Comment by BrainStone** [comment]
Well what's the issue with the UUID showing?

**Comment by SnonSS** [comment]
No, it’s not just uuid instead of nicknames, and if you delete children uuid, they return back

**Comment by Turbotailz** [comment]
Not an issue with the editor.
