### ISSUE TITLE
Selecting outdated single-server versions in the download quiz always suggests Travertine

### ISSUE THREAD

**Issue by NoahvdAa** [LuckPerms/LuckPermsWeb#402]
When selecting an outdated version of single-server software, the quiz always tells you your BungeeCord version is outdated and suggests you should use Travertine instead.

Reproduction:
- Open the downloads quiz
- Select **Single Server**
- Select any of the options
- Choose the oldest version

![](https://i.noah.pm/QoECS8.gif)

**Comment by Turbotailz** [comment]
Fixed in #409
