### ISSUE TITLE
Provide button in web apps to delete information

### ISSUE THREAD

**Issue by LoganDark** [LuckPerms/LuckPermsWeb#404]
### Description

After uploading a tree view and having a look, it would be useful to have a delete button I can use to instantly wipe that information from LP's servers.

### Proposed Behavior

Provide a delete button in the web apps (tree view, etc), that can be pressed by anyone with access to the URL, and instantly deletes the data from LP's servers (link no longer works).

**Comment by underscore11code** [comment]
Yes, selfhosting is possible, although I wouldn't recommend attempting it unless you have experience setting up web apps before. Guide @ https://luckperms.net/wiki/Self-hosting-the-web-interfaces.

> I feel like one undeletable record is quite enough...

While not user-deletable, all of LP's stuff does auto-delete from bytebin, main data (editor, tree etc) after 1w, and applyedits data after 1h (iirc, numbers might be wrong).
