### ISSUE TITLE
Ctrl+clicking links in the wiki sidebar does not open them in a new tab

### ISSUE THREAD

**Issue by LoganDark** [LuckPerms/LuckPermsWeb#405]
Middle-clicking works as intended, but Windows and macOS trackpads do not have middle click (Linux trackpads do).

**Comment by Turbotailz** [comment]
Thanks :) should be fixed shortly.

**Comment by LoganDark** [comment]
> Thanks :) should be fixed shortly.

I noticed that article links perform a full browser navigation instead of an SPA navigation. The sidebar links perform an SPA navigation without having to refresh the page. Is there a way to have the best of both worlds (clicking intrawiki links doesn't require a page refresh, but ctrl+click can still be used)?

**Comment by Turbotailz** [comment]
Hmm, that's weird. I can see this happening as well but only for some links. Could you make another issue for that one?
