### ISSUE TITLE
Default locale is weird

### ISSUE THREAD

**Issue by Vap0r1ze** [LuckPerms/LuckPermsWeb#431]
My navigator languages are like `['en-US', 'el-GR', 'el', 'en']`

**Expected Result**
my default locale is set to `en`

**Result**
my default locale is set to `el`

This happens because the language store doesn't compare the navigator languages with optional national varieties in mind

**Comment by Turbotailz** [comment]
@Vap0r1ze can you please see if this build fixes it: https://deploy-preview-433--luckperms.netlify.app/
