### ISSUE TITLE
Broken styles in production 

### ISSUE THREAD

**Issue by PoProstuMieciek** [LuckPerms/LuckPermsWeb#432]
Steps taken:
1. `npm install`
2. `npm run build`
3. setup a docker container with nginx serving files from `/dist`

This is how the website looks:
![image](https://user-images.githubusercontent.com/44976946/195974488-807abe9f-69e8-471d-b15e-43a2067c37b9.png)

This is what requests have been made:
![image](https://user-images.githubusercontent.com/44976946/195974503-f18470c5-cbf1-4693-b4d7-32a0995bf826.png)
Nothing failed so that's weird. Styles are loaded so it's not my nginx.conf's fault.

No errors in console.

**Comment by PoProstuMieciek** [comment]
`npm run serve` works fine tho, everything just fine

**Comment by PoProstuMieciek** [comment]
yeah and @lucko that's pretty urgent, i would really appreciate a quick support. this doesn't sound like a complicated issue. im also trying to figure it out myself right now

**Comment by Turbotailz** [comment]
This is likely an issue with your setup or browser. Our live website is not having any issues, nor am I having issues with serving the built files on my local machine.

Have you tried using a different browser?

**Comment by Turbotailz** [comment]
There are some points to consider when self-hosting the web interface: 
https://github.com/LuckPerms/web-installer#important-things-to-know-if-you-are-self-hosting
