### ISSUE TITLE
Suggestion to Change RSASSA-PKCS1-v1_5 Padding Mode for Improved Security

### ISSUE THREAD

**Issue by tianjk99** [LuckPerms/LuckPermsWeb#466]
Please check if there is an issue with signing using RSASSA-PKCS1-v1_5 padding mode.
1. src/util/ws.js, line 31
2. src/util/ws.js, line 290
3. src/util/ws.js, line 304

It's important to note that the PKCS#1 v1.5 padding scheme is considered insecure due to vulnerabilities, such as the RSA-PKCS1-v1_5-Attack in RSA signatures. To enhance the security of your code, I would recommend considering a switch to the RSASSA-PSS (Probabilistic Signature Scheme) padding scheme.

**Comment by lucko** [comment]
Resolved by https://github.com/LuckPerms/LuckPermsWeb/commit/93a2c3114a66d5d7570dd093da751edc1faf6df5
