### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by 8MiYile** [LuckPerms/LuckPermsWeb#80]
This website need Chinese Language ,Because have many Chinese people used this plugin,but they don't know how can edit group, 
So if you look this message ,reply me ,thanks.

**Comment by lucko** [comment]
Would accept any PR adding support for multiple languages.

**Comment by Turbotailz** [comment]
@TRose2000 just suggested this on Discord as well. They translated the home page to Dutch, I'll just leave the screenshot here.
![image](https://user-images.githubusercontent.com/10846855/54172090-c1b97d00-44e1-11e9-85d5-6bb43ef52ee8.png)

I can possibly add multi-language support in the re-work I'm doing. @lucko could you rename this to something like "Multi-language support" :)

**Comment by Turbotailz** [comment]
@TRose2000 has a fork now with the translated data which will be useful
https://github.com/TRose2000/LuckPermsWeb/tree/dutch-translation

**Comment by 8MiYile** [comment]
https://github.com/lucko/LuckPermsWeb/pull/82

**Comment by chenxuuu** [comment]
我觉得都用这东西了，还看不懂英文的话是不是不太适合搞这个。。。

不过多语言的确利于推广
multi-language support will attract more users

**Comment by RedstoneFuture** [comment]
I suggest instead a parallel installation with the orther language based the same resource. If you have multi-language support on the website you must have multi-language support for the ingame messages too, I think.

**Comment by 8MiYile** [comment]
Language: Chinese
https://luckperms.8mi.tech

**Comment by 8MiYile** [comment]
How can i add language in the code?

**Comment by Turbotailz** [comment]
Translations can now be done by adding languages to the `src/messages/` folder. An example is the [en.js](https://github.com/LuckPerms/LuckPermsWeb/blob/master/src/messages/en.js) file, you can copy this and rename it to whatever language you plan to use. 

Once you've created the language file, you can import and use it [here](https://github.com/LuckPerms/LuckPermsWeb/blob/master/src/i18n.js).

Please consider contributing to the project by PRing different languages. Once we get enough languages completed we can then look to adding a toggle option to choose which language to be used (and possibly detecting the client's language and switching to it automatically).

**Comment by martijnpu** [comment]
Why not make an option on the official website to change language?

**Comment by Turbotailz** [comment]
> Why not make an option on the official website to change language?

It's on the way, sorry!
